version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: vbcc_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

//docker exec -it vbcc_mongodb mongosh -u admin -p admin123
//use vbcc_data
//db.users.find().limit(5).pretty()

