FROM golang:1.24.3 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/server

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/app .

COPY --from=builder /app/config ./config
COPY --from=builder /app/wallet ./wallet
COPY --from=builder /app/keystore ./keystore

EXPOSE 8080

CMD ["./app"]
