services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vbcc_backend
    ports:
      - "8080:8080"
    volumes:
      - ./wallet:/root/wallet
      - ./keystore:/root/keystore
      - ./internal/config:/root/internal/config
    env_file:
      - .env
    depends_on:
      - mongodb
      - minio

  mongodb:
    image: mongo:latest
    container_name: vbcc_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  minio:
    image: quay.io/minio/minio:latest
    container_name: vbcc_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  mongo-data:
  minio-data:
